#!/bin/bash
set -ueo pipefail

if ! lsmod | grep -q kvm; then
	echo "Loading KVM module"
	modprobe -vv kvm-amd nested=1
fi

if ! [ -e /dev/kvm ]; then
	echo "Making kvm device"
	mknod /dev/kvm c 10 "$(grep '\<kvm\>' /proc/misc | cut -f 1 -d' ')"
fi

echo 'nameserver 4.2.2.2' > /guest/etc/resolv.conf

exec qemu-system-x86_64 \
	-enable-kvm \
	-cpu host \
	-m 8G \
	-smp 2 \
	-nographic \
	-kernel /guest/boot/vmlinuz-* \
	-initrd /guest/boot/initrd.img-* \
	-fsdev local,id=root,path=/guest,security_model=none \
	-device virtio-9p-pci,fsdev=root,mount_tag=rpart \
	-net nic,model=e1000e \
	-net user,hostfwd=tcp::22000-:22 \
	-append 'root=rpart rw rootfstype=9p rootflags=trans=virtio,version=9p2000.L,posixacl,cache=fscache console=ttyS0 net.ifnames=0 biosdevname=0'
